### ISSUE TITLE
dbfs.Upload failing silently

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/plugin-databricks#113]
### Describe the issue

```
      - id: databricks_store
        type: io.kestra.plugin.databricks.dbfs.Upload
        authentication:
          token: "{{secret('databricks-token')}}"
        host: "{{secret('databricks-host')}}"
        from: "{{trigger.uri}}"
        to: '/Workspace/Shared/staging.json'
```

File is not uploaded, however task succeeds without any logs 

![Image](https://github.com/user-attachments/assets/8fb83952-4d2e-4ec5-a029-52adae985228)

### Environment

- Kestra Version: develop
