### ISSUE TITLE
Allow any list parameters into the Databricks job

### ISSUE THREAD

**Issue by vivane** [kestra-io/plugin-databricks#44]
### Feature description

Parameters for the Databricks job are expected to be an explicit array of strings. Anything else which is resolved into an array of string is not accepted.

For example, parameters are defined as a JSON array:
```
inputs:
  - name: SCRIPT_PARAMETERS
    type: JSON
    required: true
    defaults: |
      { "arguments": ["--a", "A","--b", "B"] }
tasks:
  - id: submitRun
    type: io.kestra.plugin.databricks.job.SubmitRun
    host: "{{ inputs.DATABRICKS_HOST }}"
    runTasks:
      - existingClusterId: "{{ inputs.EXISTING_CLUSTER_ID }}"
        taskKey: pysparkTask
        sparkPythonTask:
          pythonFile: "{{ inputs.PYTHON_FILE_PATH }}"
          sparkPythonTaskSource: WORKSPACE
          parameters: ...
    waitForCompletion: PT5M
```
When parameters are submitted as explicit array of string...
```
          parameters: ["{{ inputs.SCRIPT_PARAMETERS.arguments }}"]
```
...then job receives them as a single string.

When parameters are submitted as a reference to JSON array...
```
          parameters: {{ inputs.SCRIPT_PARAMETERS.arguments }}
```
...Kestra gives the deserialization error.

It is necessary to accept anything which is resolved into the list. For example, a JSON array or string with split filter.
