### ISSUE TITLE
Databricks SQL Authenticate with service principal (OAuth token)

### ISSUE THREAD

**Issue by fbacker** [kestra-io/plugin-databricks#99]
### Feature description

Make it possible to use azure service principal when using 'io.kestra.plugin.databricks.sql.Query'.

I've managed to use a service principal by properties. to get the secret I needed to create it from databricks, I couldn't use the entra service principal secret. 

Another issue with using this "temporary solution" is that I couldn't get secrets to work, so I needed to add the oauth2secret and clientid as plaintext.

create secret for service principal
databricks manage account
user management -> service principals
create an OAuth secret, can't use from entra

```
  - id: databricks_sql
    type: io.kestra.plugin.databricks.sql.Query
    properties:
      AuthMech: "11"
      Auth_Flow: "1"
      OAuth2ClientId: "guid for entra service principal"
      OAuth2Secret: "secret created from databricks"
    host: myname.azuredatabricks.net
    httpPath: /sql/1.0/warehouses/my-id
    sql: select 1
 ```

More info can be found at slack https://kestra-io.slack.com/archives/C03FQKXRK3K/p1736944826740719

**Comment by anna-geller** [comment]
**from Slack:**

How can I authenticate databricks with a service principal from azure?
is there a specific way to globally set tenant,client,secret in the kestra configuration? I've tried setting kestra config. However id doesn't seem like the JavaClass for query extends AbstractTask as CreateJob? https://github.com/kestra-io/plugin-databricks/blob/master/src/main/java/io/kestra/plugin/databricks/AbstractTask.java 

So this doesn't work (if I'm doing it correctly :/)
```yaml
- type: io.kestra.plugin.databricks.sql.Query
  values:
    azureTenantId: tenant-guid
    azureClientId: client-guid
    azureClientSecret: password
```

I've tried manually getting the token to pass as variable but getting 401 error.
```yaml
  - id: get_access_token
    type: io.kestra.plugin.azure.auth.OauthAccessToken
    tenantId: "{{ secret('AZURE_TENANT_ID') }}"
    clientId: "{{ secret('AZURE_CLIENT_ID') }}"
    clientSecret: "{{ secret('AZURE_CLIENT_SECRET') }}"  

  - id: do_things
    type: io.kestra.plugin.databricks.sql.Query
    accessToken: "{{ outputs.get_access_token.accessToken }}"
```
looking at databricks docs https://docs.databricks.com/en/integrations/jdbc/authentication.html#oauth-20-tokens is seems that if we are using a service principal, we need to set other values than using the PAT.

Workaround: 
1. create secret for service principal
databricks manage account
user management -> service principals
create an OAuth secret, can't use from entra
2. add properties to fix security
```yaml
  - id: databricks_sql
    type: io.kestra.plugin.databricks.sql.Query
    properties:
      AuthMech: "11"
      Auth_Flow: "1"
      OAuth2ClientId: "guid for entra service principal"
      OAuth2Secret: "secret created from databricks"
    host: myname.azuredatabricks.net
    httpPath: /sql/1.0/warehouses/my-id
    sql: select 1
```
